{{ if .Values.scalyr.k8s.installExplorerDependencies }}
apiVersion: v1
automountServiceAccountToken: false
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: kube-state-metrics
    app.kubernetes.io/version: 2.5.0
  {{- include "scalyr-helm.dependencies-labels" . | nindent 4 }}
  name: kube-state-metrics
  namespace: {{ .Release.Namespace }}
{{- end }}
