# Values file used by end to end tests
controllerType: "daemonset"
podLabels:
  test: "true"
scalyr:
  apiKey: "REPLACE_ME"
  k8s:
    clusterName: "k8s-explorer-e2e-tests"
    verifyKubeletQueries: false
  base64Config: true
  config:
    test-config.json: e3NlcnZlcl9hdHRyaWJ1dGVzOiB7YXR0cmlidXRlMTogInZhbHVlMSIsYXR0cmlidXRlMjogInZhbHVlMiIsfSx9

image:
  distro: "IMAGE_TYPE"
