# Values file used by end to end tests
controllerType: "deployment"
podLabels:
  test: "true"
scalyr:
  apiKey: "REPLACE_ME"
  k8s:
    clusterName: "k8s-explorer-e2e-tests"
    verifyKubeletQueries: false
