# Workflow which is used for creating and publishing a new helm chart artifact on push / merge to
# main branch

name: "Release Helm Chart"

on:
  # We only run this workflow if both test workflows complete successfully
  # workflow_run:
  #   workflows:
  #     # TODO: We can't depend on two workflows using "AND" condition (aka both workflows need to
  #     # pass), so we just depend on the longer one. When specifying multiple workflows it uses
  #     # "OR" behavior.
  #     - "End to End Tests"
  #   branches:
  #     - main
  #   types:
  #     - completed
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    #if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@18bc76811624f360dbd7f18c2d4ecb32c7b87bab # v1.1
        with:
          version: v3.7.0

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.2.1
        env:
          CR_TOKEN: "${{ github.token }}"
        with:
          charts_dir: charts

      - name: Write latest stable version to info.json file
        run: |
          # We write latest stable version info to JSON file which we can query for displaying
          # badge in the readme
          CHART_VERSION=$(cat charts/scalyr-agent/Chart.yaml | grep "version: " | sed "s/version: //g" | tr -d "\n")
          echo '{"scalyrAgent": "v'${CHART_VERSION}'"}' > info.json
          git fetch origin
          git checkout gh-pages
          cat info.json
          git add info.json
          git commit -m "Update info.json file" || true
          git push origin gh-pages

      - name: Notify Slack on Failure
        # NOTE: github.ref is set to pr ref (and not branch name, e.g. refs/pull/28/merge) for pull
        # requests and that's why we need this special conditional and check for github.head_ref in
        # case of PRs
        if: ${{ failure() && (github.ref == 'refs/heads/main' || github.head_ref == 'main') }}
        uses: act10ns/slack@e4e71685b9b239384b0f676a63c32367f59c2522 # v1.2.2
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          channel: '#cloud-tech'
